/* Automatically generated by litmus */

#ifndef _TESTCASE_H_
#define _TESTCASE_H_

#define NUM_PROCESSES 2
#define NUM_ITERATIONS 100
#define NUM_VARS 2
#define NUM_LOCS 65536
#define LOC_GRAIN 1
#define LEN_OUTCOME 2
#define OUTCOME_NAMES { "0:x5","1:x5" }
#define OUTCOME_SOUGHT { 1,1 }


#endif
